[package]
name = "blenny"
version = "0.1.0"
edition = "2024"

[dependencies]
blenny-macros = { path = "../blenny-macros" }
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }
inventory = "0.3"
tera = "1"
rust-embed = "8"
notify = { version = "6", optional = true }
