[package]
name = "blenny"
version = "0.1.0"
edition = "2024"

[features]
default = []
datastar-sse = ["datastar"]

[dependencies]
blenny-macros = { path = "../blenny-macros" }
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace"] }
inventory = "0.3"
tera = "1"
rust-embed = "8"
notify = { version = "8", features = ["macos_kqueue"] }
tokio-stream = "0.1"
async-stream = "0.3"
jsonwebtoken = { version = "10", features = ["aws_lc_rs"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
axum-extra = { version = "0.12", features = ["cookie"] }
cookie = "0.18"
time = "0.3"
datastar = { version = "0.3", optional = true }
